SIIS
SIIS::N
Number of nodes.
SIIS::tm
Discrete time units.
int SIIS.take_sample
SIIS::smp_size
sample size
SIIS::theta
Margin off error to see if a Meme won in sampling, if less than theta no clear winner.
int SIIS.beta1
int SIIS.beta2
int SIIS.delta1
int SIIS.delta2
int SIIS.M1_Wins
int SIIS.M2_Wins
int SIIS.No_win
list SIIS.allNodes
int SIIS.tot_inf1
int SIIS.old_inf1
int SIIS.old_inf2
int SIIS.tot_inf2
int SIIS.total_M1
int SIIS.total_M2
int SIIS.total_S
tuple SIIS::A1
SETUP#################################################################################################################################################################################################.
Make sure adj are symmetric and values are 2 or 1 By making it symmetric, we are making sure if Node 1 is connected to Node 2, then Node 2 is also connected to Node 1.
tuple SIIS::A2
tuple SIIS.S1
create System Matrices
tuple SIIS.S2
SIIS.eigenValues1
get Eigen Values
SIIS.eigenVectors1
SIIS.eigenValues2
SIIS.eigenVectors2
SIIS.idx
sort list of found eigenvalues to find the largest one
SIIS.node
Using our created Node data type, we fill a list with nodes of length N.
SIIS.key
sort nodes by ID number
SIIS.id
SIIS.reverse
SIIS.infected_meme1
create first list of infected nodes holds org sets to use for multiple lists
SIIS.infected_meme2
int SIIS::edge
Run Simulation without Supression.
MAIN LOOP################################################################################################################################################################################ Run with Suppression Methods
def SIIS.randomRem()
randomRem picks a random node
References removeNode.
def SIIS.randomNeigh(pick)
randomNeigh
pick What edge to delete node from picks a random neighbor of a random node
References removeNode.
def SIIS.max_degree(edge)
max_degree
edge What edge to delete node from removes node max degree or most connections
References removeNode.
def SIIS.removeNode(nodea)
removeNode
nodea The node to be deleted removes the node being passed
Referenced by max_degree, randomNeigh, randomRem.
def SIIS.set_simulation()
set_simulation
sets up infected lists for infection set infected counts to empty set array of stats to empty sets x axis as empty
References count.
Referenced by run_sim.
def SIIS.count()
count counts number of currently infected sets total_M values to current values
Referenced by run_sim, set_simulation.
def SIIS.run_sim()
run_sim() carries out actual simulation uses for loop t inside time
References count, set_simulation.
def SIIS.plot_res(pause, supress, spr)
plot_res
plots histogram and time graph of simulation pause if true does not plot but sets up graph until ran again with pause = false supress if true plot supression methods as well spr hold name supression method graphed to name on graph