.TH "C:/Users/Bobby the Kid's/Documents/turtledefense/TurtleDefense/PythonTrial/SIIR Directory Reference" 3 "Thu May 5 2022" "Version 3" "Turle Defense_SIIS_python_simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Bobby the Kid's/Documents/turtledefense/TurtleDefense/PythonTrial/SIIR Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBSIIS\&.py\fP"
.br
.in -1c
