.TH "C:/Users/Bobby the Kid's/Documents/turtledefense/TurtleDefense/PythonTrial Directory Reference" 3 "Thu May 5 2022" "Version 3" "Turle Defense_SIIS_python_simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
C:/Users/Bobby the Kid's/Documents/turtledefense/TurtleDefense/PythonTrial Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBSIIR\fP"
.br
.in -1c
