.TH "SIIS.State" 3 "Thu May 5 2022" "Version 3" "Turle Defense_SIIS_python_simulation" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SIIS.State \- Enumeration for States\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits enum\&.Enum\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "int \fBS\fP = 0"
.br
.ti -1c
.RI "int \fBI1\fP = 1"
.br
.ti -1c
.RI "int \fBI2\fP = 2"
.br
.in -1c
.SH "Detailed Description"
.PP 
Enumeration for States\&. 
.SH "Member Data Documentation"
.PP 
.SS "int SIIS\&.State\&.I1 = 1\fC [static]\fP"

.SS "int SIIS\&.State\&.I2 = 2\fC [static]\fP"

.SS "int SIIS\&.State\&.S = 0\fC [static]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Turle Defense_SIIS_python_simulation from the source code\&.
